var songs = new Map([
    [["Finland",2004],["Jari Sillanpaa","Takes 2 to Tango"]],
    [["Belarus",2004],["Aleksandra and Konstantin","My Galileo"]],
    [["Switzerland",2004],["Piero and the MusicStars","Celebrate"]],
    [["Latvia",2004],["Fomins and Kleins","Dziesma par laimi"]],
    [["Israel",2004],["David D'Or","Leha'amin"]],
    [["Andorra",2004],["Marta Roure","Jugarem a estimar-nos"]],
    [["Portugal",2004],["Sofia Vitoria","Foi magia"]],
    [["Malta",2004],["Julie and Ludwig","On Again... Off Again"]],
    [["Monaco",2004],["Maryon","Notre planete"]],
    [["Greece",2004],["Sakis Rouvas","Shake It"]],
    [["Ukraine",2004],["Ruslana","Wild Dances"]],
    [["Lithuania",2004],["Linas and Simona","What's Happened to Your Love"]],
    [["Albania",2004],["Anjeza Shahini","The Image of You"]],
    [["Cyprus",2004],["Lisa Andreas","Stronger Every Minute"]],
    [["Macedonia",2004],["Tose Proeski","Life"]],
    [["Slovenia",2004],["Platin","Stay Forever"]],
    [["Estonia",2004],["Neiokoso","Tii"]],
    [["Croatia",2004],["Ivan Mikulic","You Are the Only One"]],
    [["Denmark",2004],["Tomas Thordarson","Shame on You"]],
    [["Serbia and Montenegro",2004],["Zeljko Joksimovic and Ad-Hoc Orchestra","Lane moje"]],
    [["Bosnia and Herzegovina",2004],["Deen","In the Disco"]],
    [["the Netherlands",2004],["Re-union","Without You"]],
    [["Spain",2004],["Ramon","Para llenarme de ti"]],
    [["Austria",2004],["Tie Break","Du bist"]],
    [["Norway",2004],["Knut Anders Sorum","High"]],
    [["France",2004],["Jonatan Cerrada","A chaque pas"]],
    [["Germany",2004],["Max","Can't Wait Until Tonight"]],
    [["Belgium",2004],["Xandee","1 Life"]],
    [["Russia",2004],["Julia Savicheva","Believe Me"]],
    [["Iceland",2004],["Jonsi","Heaven"]],
    [["Ireland",2004],["Chris Doran","If My World Stopped Turning"]],
    [["Poland",2004],["Blue Cafe","Love Song"]],
    [["the United Kingdom",2004],["James Fox","Hold On to Our Love"]],
    [["Turkey",2004],["Athena","For Real"]],
    [["Romania",2004],["Sanda","I Admit"]],
    [["Sweden",2004],["Lena Philipsson","It Hurts"]],
    [["Austria",2005],["Global.Kryner","Y asi"]],
    [["Lithuania",2005],["Laura and the Lovers","Little by Little"]],
    [["Portugal",2005],["2B","Amar"]],
    [["Moldova",2005],["Zdob si Zdub","Boonika bate doba"]],
    [["Latvia",2005],["Walters and Kazha","The War Is Not Over"]],
    [["Monaco",2005],["Lise Darly","Tout de moi"]],
    [["Israel",2005],["Shiri Maimon","HaSheket SheNish'ar"]],
    [["Belarus",2005],["Angelica Agurbash","Love Me Tonight"]],
    [["the Netherlands",2005],["Glennis Grace","My Impossible Dream"]],
    [["Iceland",2005],["Selma","If I Had Your Love"]],
    [["Belgium",2005],["Nuno Resende","Le Grand soir"]],
    [["Estonia",2005],["Suntribe","Let's Get Loud"]],
    [["Norway",2005],["Wig Wam","In My Dreams"]],
    [["Romania",2005],["Luminita Anghel and Sistem","Let Me Try"]],
    [["Hungary",2005],["Nox","Forogj, vilag"]],
    [["Finland",2005],["Geir Ronning","Why"]],
    [["Macedonia",2005],["Martin Vucic","Make My Day"]],
    [["Andorra",2005],["Marian van de Wal","La mirada interior"]],
    [["Switzerland",2005],["Vanilla Ninja","Cool Vibes"]],
    [["Croatia",2005],["Boris Novkovicfeat.Lado Members","Vukovi umiru sami"]],
    [["Bulgaria",2005],["Kaffe","Lorraine"]],
    [["Ireland",2005],["Donna and Joe","Love?"]],
    [["Slovenia",2005],["Omar Naber","Stop"]],
    [["Denmark",2005],["Jakob Sveistrup","Talking to You"]],
    [["Poland",2005],["Ivan and Delfin","Czarna dziewczyna"]],
    [["the United Kingdom",2005],["Javine","Touch My Fire"]],
    [["Malta",2005],["Chiara","Angel"]],
    [["Turkey",2005],["Gulseren","Rimi Rimi Ley"]],
    [["Albania",2005],["Ledina Celo","Tomorrow I Go"]],
    [["Cyprus",2005],["Constantinos Christoforou","Ela Ela"]],
    [["Spain",2005],["Son de Sol","Brujeria"]],
    [["Serbia and Montenegro",2005],["No Name","Zauvijek moja"]],
    [["Sweden",2005],["Martin Stenmarck","Las Vegas"]],
    [["Ukraine",2005],["GreenJolly","Razom nas bahato"]],
    [["Germany",2005],["Gracia","Run & Hide"]],
    [["Greece",2005],["Helena Paparizou","My Number One"]],
    [["Russia",2005],["Natalia Podolskaya","Nobody Hurt No One"]],
    [["Bosnia and Herzegovina",2005],["Feminnem","Call Me"]],
    [["France",2005],["Ortal","Chacun pense a soi"]],
    [["Armenia",2006],["Andre","Without Your Love"]],
    [["Bulgaria",2006],["Mariana Popova","Let Me Cry"]],
    [["Slovenia",2006],["Anzej Dezan","Mr Nobody"]],
    [["Andorra",2006],["Jenny","Sense tu"]],
    [["Belarus",2006],["Polina Smolova","Mum"]],
    [["Albania",2006],["Luiz Ejlli","Zjarr e ftohte"]],
    [["Belgium",2006],["Kate Ryan","Je t'adore"]],
    [["Ireland",2006],["Brian Kennedy","Every Song Is a Cry for Love"]],
    [["Cyprus",2006],["Annet Artani","Why Angels Cry"]],
    [["Monaco",2006],["Severine Ferrer","La Coco-Dance"]],
    [["Macedonia",2006],["Elena Risteska","Ninanajna"]],
    [["Poland",2006],["Ich Troje[g]","Follow My Heart"]],
    [["Russia",2006],["Dima Bilan","Never Let You Go"]],
    [["Turkey",2006],["Sibel Tuzun","Super Star"]],
    [["Ukraine",2006],["Tina Karol","Show Me Your Love"]],
    [["Finland",2006],["Lordi","Hard Rock Hallelujah"]],
    [["the Netherlands",2006],["Treble","Amambanda"]],
    [["Lithuania",2006],["LT United","We Are the Winners"]],
    [["Portugal",2006],["Nonstop","Coisas de nada"]],
    [["Sweden",2006],["Carola","Invincible"]],
    [["Estonia",2006],["Sandra","Through My Window"]],
    [["Bosnia and Herzegovina",2006],["Hari Mata Hari","Lejla"]],
    [["Iceland",2006],["Silvia Night","Congratulations"]],
    [["Switzerland",2006],["six4one","If We All Give a Little"]],
    [["Moldova",2006],["Arsenium feat. Natalia Gordienko and Connect-R","Loca"]],
    [["Israel",2006],["Eddie Butler","Together We Are One"]],
    [["Latvia",2006],["Vocal Group Cosmos","I Hear Your Heart"]],
    [["Norway",2006],["Christine Guldbrandsen","Alvedansen"]],
    [["Spain",2006],["Las Ketchup","Bloody Mary"]],
    [["Malta",2006],["Fabrizio Faniello","I Do"]],
    [["Germany",2006],["Texas Lightning","No No Never"]],
    [["Denmark",2006],["Sidsel Ben Semmane","Twist of Love"]],
    [["Romania",2006],["Mihai Traistariu","Tornero"]],
    [["the United Kingdom",2006],["Daz Sampson","Teenage Life"]],
    [["Greece",2006],["Anna Vissi","Everything"]],
    [["France",2006],["Virginie Pouchain","Il etait temps"]],
    [["Croatia",2006],["Severina","Moja stikla"]],
    [["Bulgaria",2007],["Elitsa Todorova and Stoyan Yankoulov","Water"]],
    [["Israel",2007],["Teapacks","Push the Button"]],
    [["Cyprus",2007],["Evridiki","Comme ci, comme ca"]],
    [["Belarus",2007],["Koldun","Work Your Magic"]],
    [["Iceland",2007],["Eirikur Hauksson","Valentine Lost"]],
    [["Georgia",2007],["Sopho","Visionary Dream"]],
    [["Montenegro",2007],["Stevan Faddy","'Ajde, kroci"]],
    [["Switzerland",2007],["DJ BoBo","Vampires Are Alive"]],
    [["Moldova",2007],["Natalia Barbu","Fight"]],
    [["the Netherlands",2007],["Edsilia Rombley","On Top of the World"]],
    [["Albania",2007],["Frederik Ndoci","Hear My Plea"]],
    [["Denmark",2007],["DQ","Drama Queen"]],
    [["Croatia",2007],["Dragonfly feat. Dado Topic","Vjerujem u ljubav"]],
    [["Poland",2007],["The Jet Set","Time to Party"]],
    [["Serbia",2007],["Marija Serifovic","Molitva"]],
    [["Czech Republic",2007],["Kabat","Mala dama"]],
    [["Portugal",2007],["Sabrina","Danca comigo"]],
    [["Macedonia",2007],["Karolina","Mojot svet"]],
    [["Norway",2007],["Guri Schanke","Ven a bailar conmigo"]],
    [["Malta",2007],["Olivia Lewis","Vertigo"]],
    [["Andorra",2007],["Anonymous","Salvem el mon"]],
    [["Hungary",2007],["Magdi Ruzsa","Unsubstantial Blues"]],
    [["Estonia",2007],["Gerli Padar","Partners in Crime"]],
    [["Belgium",2007],["The KMG's","LovePower"]],
    [["Slovenia",2007],["Alenka Gotar","Cvet z juga"]],
    [["Turkey",2007],["Kenan Dogulu","Shake It Up Sekerim"]],
    [["Austria",2007],["Eric Papilaya","Get a Life - Get Alive"]],
    [["Latvia",2007],["Bonaparti.lv","Questa notte"]],
    [["Bosnia and Herzegovina",2007],["Marija Sestic","Rijeka bez imena"]],
    [["Spain",2007],["D'Nash","I Love You Mi Vida"]],
    [["Ireland",2007],["Dervish","They Can't Stop the Spring"]],
    [["Finland",2007],["Hanna Pakarinen","Leave Me Alone"]],
    [["Lithuania",2007],["4Fun","Love or Leave"]],
    [["Greece",2007],["Sarbel","Yassou Maria"]],
    [["Sweden",2007],["The Ark","The Worrying Kind"]],
    [["France",2007],["Les Fatals Picards","L'Amour a la francaise"]],
    [["Russia",2007],["Serebro","Song #1"]],
    [["Germany",2007],["Roger Cicero","Frauen regier'n die Welt"]],
    [["Ukraine",2007],["Verka Serduchka","Dancing Lasha Tumbai"]],
    [["the United Kingdom",2007],["Scooch","Flying the Flag (For You)"]],
    [["Romania",2007],["Todomondo","Liubi, Liubi, I Love You"]],
    [["Armenia",2007],["Hayko","Anytime You Need"]],
    [["Montenegro",2008],["Stefan Filipovic","Zauvijek volim te"]],
    [["Israel",2008],["Boaz","The Fire in Your Eyes"]],
    [["Estonia",2008],["Kreisiraadio","Leto svet"]],
    [["Moldova",2008],["Geta Burlacu","A Century of Love"]],
    [["San Marino",2008],["Miodio","Complice"]],
    [["Belgium",2008],["Ishtar","O Julissi"]],
    [["Azerbaijan",2008],["Elnur and Samir","Day After Day"]],
    [["Slovenia",2008],["Rebeka Dremelj","Vrag naj vzame"]],
    [["Norway",2008],["Maria","Hold On Be Strong"]],
    [["Poland",2008],["Isis Gee","For Life"]],
    [["Ireland",2008],["Dustin the Turkey","Irelande Douze Pointe"]],
    [["Andorra",2008],["Gisela","Casanova"]],
    [["Bosnia and Herzegovina",2008],["Laka","Pokusaj"]],
    [["Armenia",2008],["Sirusho","Qele, Qele"]],
    [["the Netherlands",2008],["Hind","Your Heart Belongs to Me"]],
    [["Finland",2008],["Terasbetoni","Missa miehet ratsastaa"]],
    [["Romania",2008],["Nico and Vlad","Pe-o margine de lume"]],
    [["Russia",2008],["Dima Bilan","Believe"]],
    [["Greece",2008],["Kalomira","Secret Combination"]],
    [["Iceland",2008],["Euroband","This Is My Life"]],
    [["Sweden",2008],["Charlotte Perrelli","Hero"]],
    [["Turkey",2008],["Mor ve Otesi","Deli"]],
    [["Ukraine",2008],["Ani Lorak","Shady Lady"]],
    [["Lithuania",2008],["Jeronimas Milius","Nomads in the Night"]],
    [["Albania",2008],["Olta Boka","Zemren e lame peng"]],
    [["Switzerland",2008],["Paolo Meneguzzi","Era stupendo"]],
    [["Czech Republic",2008],["Tereza Kerndlova","Have Some Fun"]],
    [["Belarus",2008],["Ruslan Alehno","Hasta la vista"]],
    [["Latvia",2008],["Pirates of the Sea","Wolves of the Sea"]],
    [["Croatia",2008],["Kraljevi ulice and 75 Cents","Romanca"]],
    [["Bulgaria",2008],["Deep Zone and Balthazar","DJ, Take Me Away"]],
    [["Denmark",2008],["Simon Mathew","All Night Long"]],
    [["Georgia",2008],["Diana Gurtskaya","Peace Will Come"]],
    [["Hungary",2008],["Csezy","Candlelight"]],
    [["Malta",2008],["Morena","Vodka"]],
    [["Cyprus",2008],["Evdokia Kadi","Femme Fatale"]],
    [["Macedonia",2008],["Tamara, Vrcak and Adrijan","Let Me Love You"]],
    [["Portugal",2008],["Vania Fernandes","Senhora do mar (negras aguas)"]],
    [["the United Kingdom",2008],["Andy Abraham","Even If"]],
    [["Germany",2008],["No Angels","Disappear"]],
    [["France",2008],["Sebastien Tellier","Divine"]],
    [["Spain",2008],["Rodolfo Chikilicuatre","Baila el Chiki Chiki"]],
    [["Serbia",2008],["Jelena Tomasevic feat. Bora Dugic","Oro"]],
    [["Montenegro",2009],["Andrea Demirovic","Just Get Out of My Life"]],
    [["Czech Republic",2009],["Gipsy.cz","Aven Romale"]],
    [["Belgium",2009],["Copycat","Copycat"]],
    [["Belarus",2009],["Petr Elfimov","Eyes That Never Lie"]],
    [["Sweden",2009],["Malena Ernman","La Voix"]],
    [["Armenia",2009],["Inga and Anush","Jan Jan"]],
    [["Andorra",2009],["Susanne Georgi","La teva decisio (Get a Life)"]],
    [["Switzerland",2009],["Lovebugs","The Highest Heights"]],
    [["Turkey",2009],["Hadise","Dum Tek Tek"]],
    [["Israel",2009],["Noa and Mira Awad","There Must Be Another Way"]],
    [["Bulgaria",2009],["Krassimir Avramov","Illusion"]],
    [["Iceland",2009],["Yohanna","Is It True?"]],
    [["Macedonia",2009],["Next Time","Nesto sto kje ostane"]],
    [["Romania",2009],["Elena","The Balkan Girls"]],
    [["Finland",2009],["Waldo's People","Lose Control"]],
    [["Portugal",2009],["Flor-de-Lis","Todas as ruas do amor"]],
    [["Malta",2009],["Chiara","What If We"]],
    [["Bosnia and Herzegovina",2009],["Regina","Bistra voda"]],
    [["Croatia",2009],["Igor Cukrov feat. Andrea","Lijepa Tena"]],
    [["Ireland",2009],["Sinead Mulvey and Black Daisy","Et Cetera"]],
    [["Latvia",2009],["Intars Busulis","Probka"]],
    [["Serbia",2009],["Marko Kon and Milaan","Cipela"]],
    [["Poland",2009],["Lidia Kopania","I Don't Wanna Leave"]],
    [["Norway",2009],["Alexander Rybak","Fairytale"]],
    [["Cyprus",2009],["Christina Metaxa","Firefly"]],
    [["Slovakia",2009],["Kamil Mikulcik and Nela Pociskova","Let tmou"]],
    [["Denmark",2009],["Brinck","Believe Again"]],
    [["Slovenia",2009],["Quartissimo feat. Martina","Love Symphony"]],
    [["Hungary",2009],["Zoli Adok","Dance with Me"]],
    [["Azerbaijan",2009],["Aysel and Arash","Always"]],
    [["Greece",2009],["Sakis Rouvas","This Is Our Night"]],
    [["Lithuania",2009],["Sasha Son","Love"]],
    [["Moldova",2009],["Nelly Ciobanu","Hora din Moldova"]],
    [["Albania",2009],["Kejsi Tola","Carry Me in Your Dreams"]],
    [["Ukraine",2009],["Svetlana Loboda","Be My Valentine! (Anti-Crisis Girl)"]],
    [["Estonia",2009],["Urban Symphony","Randajad"]],
    [["the Netherlands",2009],["The Toppers","Shine"]],
    [["France",2009],["Patricia Kaas","Et s'il fallait le faire"]],
    [["Russia",2009],["Anastasia Prikhodko","Mamo"]],
    [["Germany",2009],["Alex Swings Oscar Sings!","Miss Kiss Kiss Bang"]],
    [["the United Kingdom",2009],["Jade Ewen","It's My Time"]],
    [["Spain",2009],["Soraya Arnelas","La noche es para mi"]],
    [["Moldova",2010],["SunStroke Project and Olia Tira","Run Away"]],
    [["Russia",2010],["Peter Nalitch and Friends","Lost and Forgotten"]],
    [["Estonia",2010],["Malcolm Lincoln","Siren"]],
    [["Slovakia",2010],["Kristina","Horehronie"]],
    [["Finland",2010],["Kuunkuiskaajat","Tyolki ellaa"]],
    [["Latvia",2010],["Aisha","What For?"]],
    [["Serbia",2010],["Milan Stankovic","Ovo je Balkan"]],
    [["Bosnia and Herzegovina",2010],["Vukasin Brajic","Thunder and Lightning"]],
    [["Poland",2010],["Marcin Mrozinski","Legenda"]],
    [["Belgium",2010],["Tom Dice","Me and My Guitar"]],
    [["Malta",2010],["Thea Garrett","My Dream"]],
    [["Albania",2010],["Juliana Pasha","It's All About You"]],
    [["Greece",2010],["Giorgos Alkaios and Friends","Opa"]],
    [["Portugal",2010],["Filipa Azevedo","Ha dias assim"]],
    [["Macedonia",2010],["Gjoko Taneski[m]","Jas ja imam silata"]],
    [["Belarus",2010],["3+2 feat. Robert Wells","Butterflies"]],
    [["Iceland",2010],["Hera Bjork","Je ne sais quoi"]],
    [["Lithuania",2010],["InCulto","Eastern European Funk"]],
    [["Armenia",2010],["Eva Rivas","Apricot Stone"]],
    [["Israel",2010],["Harel Skaat","Milim"]],
    [["Denmark",2010],["Chanee and N'evergreen","In a Moment like This"]],
    [["Switzerland",2010],["Michael von der Heide","Il pleut de l'or"]],
    [["Sweden",2010],["Anna Bergendahl","This Is My Life"]],
    [["Azerbaijan",2010],["Safura","Drip Drop"]],
    [["Ukraine",2010],["Alyosha","Sweet People"]],
    [["the Netherlands",2010],["Sieneke","Ik ben verliefd (Sha-la-lie)"]],
    [["Romania",2010],["Paula Seling and Ovi","Playing with Fire"]],
    [["Slovenia",2010],["Ansambel Zlindra and Kalamari","Narodnozabavni rock"]],
    [["Ireland",2010],["Niamh Kavanagh","It's for You"]],
    [["Bulgaria",2010],["Miro","Angel si ti"]],
    [["Cyprus",2010],["Jon Lilygreen and the Islanders","Life Looks Better in Spring"]],
    [["Croatia",2010],["Feminnem","Lako je sve"]],
    [["Georgia",2010],["Sofia Nizharadze","Shine"]],
    [["Turkey",2010],["Manga","We Could Be the Same"]],
    [["Spain",2010],["Daniel Diges","Algo pequenito"]],
    [["Norway",2010],["Didrik Solli-Tangen","My Heart Is Yours"]],
    [["the United Kingdom",2010],["Josh Dubovie","That Sounds Good to Me"]],
    [["France",2010],["Jessy Matador","Allez Ola Ole"]],
    [["Germany",2010],["Lena","Satellite"]],
    [["Poland",2011],["Magdalena Tul","Jestem"]],
    [["Norway",2011],["Stella Mwangi","Haba Haba"]],
    [["Albania",2011],["Aurela Gace","Feel the Passion"]],
    [["Armenia",2011],["Emmy","Boom Boom"]],
    [["Turkey",2011],["Yuksek Sadakat","Live It Up"]],
    [["Serbia",2011],["Nina","Caroban"]],
    [["Russia",2011],["Alexey Vorobyov","Get You"]],
    [["Switzerland",2011],["Anna Rossinelli","In Love for a While"]],
    [["Georgia",2011],["Eldrine","One More Day"]],
    [["Finland",2011],["Paradise Oskar","Da Da Dam"]],
    [["Malta",2011],["Glen Vella","One Life"]],
    [["San Marino",2011],["Senit","Stand By"]],
    [["Croatia",2011],["Daria","Celebrate"]],
    [["Iceland",2011],["Sjonni's Friends","Coming Home"]],
    [["Hungary",2011],["Kati Wolf","What About My Dreams?"]],
    [["Portugal",2011],["Homens da Luta","A luta e alegria"]],
    [["Lithuania",2011],["Evelina Sasenko","C'est ma vie"]],
    [["Azerbaijan",2011],["Ell and Nikki","Running Scared"]],
    [["Greece",2011],["Loukas Yorkas feat. Stereo Mike","Watch My Dance"]],
    [["Bosnia and Herzegovina",2011],["Dino Merlin","Love in Rewind"]],
    [["Austria",2011],["Nadine Beiler","The Secret Is Love"]],
    [["the Netherlands",2011],["3JS","Never Alone"]],
    [["Belgium",2011],["Witloof Bay","With Love Baby"]],
    [["Slovakia",2011],["Twiins","I'm Still Alive"]],
    [["Ukraine",2011],["Mika Newton","Angel"]],
    [["Moldova",2011],["Zdob si Zdub","So Lucky"]],
    [["Sweden",2011],["Eric Saade","Popular"]],
    [["Cyprus",2011],["Christos Mylordos","San aggelos s'agapisa"]],
    [["Bulgaria",2011],["Poli Genova","Na inat"]],
    [["Macedonia",2011],["Vlatko Ilievski","Rusinka"]],
    [["Israel",2011],["Dana International","Ding Dong"]],
    [["Slovenia",2011],["Maja Keuc","No One"]],
    [["Romania",2011],["Hotel FM","Change"]],
    [["Estonia",2011],["Getter Jaani","Rockefeller Street"]],
    [["Belarus",2011],["Anastasia Vinnikova","I Love Belarus"]],
    [["Latvia",2011],["Musiqq","Angel in Disguise"]],
    [["Denmark",2011],["A Friend in London","New Tomorrow"]],
    [["Ireland",2011],["Jedward","Lipstick"]],
    [["France",2011],["Amaury Vassili","Sognu"]],
    [["Italy",2011],["Raphael Gualazzi","Madness of Love"]],
    [["the United Kingdom",2011],["Blue","I Can"]],
    [["Germany",2011],["Lena","Taken by a Stranger"]],
    [["Spain",2011],["Lucia Perez","Que me quiten lo bailao"]],
    [["Montenegro",2012],["Rambo Amadeus","Euro Neuro"]],
    [["Iceland",2012],["Greta Salome and Jonsi","Never Forget"]],
    [["Greece",2012],["Eleftheria Eleftheriou","Aphrodisiac"]],
    [["Latvia",2012],["Anmary","Beautiful Song"]],
    [["Albania",2012],["Rona Nishliu","Suus"]],
    [["Romania",2012],["Mandinga","Zaleilah"]],
    [["Switzerland",2012],["Sinplus","Unbreakable"]],
    [["Belgium",2012],["Iris","Would You?"]],
    [["Finland",2012],["Pernilla","Nar jag blundar"]],
    [["Israel",2012],["Izabo","Time"]],
    [["San Marino",2012],["Valentina Monetta","The Social Network Song (Oh Oh - Uh - Oh Oh)"]],
    [["Cyprus",2012],["Ivi Adamou","La La Love"]],
    [["Denmark",2012],["Soluna Samay","Should've Known Better"]],
    [["Russia",2012],["Buranovskiye Babushki","Party for Everybody"]],
    [["Hungary",2012],["Compact Disco","Sound of Our Hearts"]],
    [["Austria",2012],["Trackshittaz","Woki mit deim Popo"]],
    [["Moldova",2012],["Pasha Parfeny","Lautar"]],
    [["Ireland",2012],["Jedward","Waterline"]],
    [["Serbia",2012],["Zeljko Joksimovic","Nije ljubav stvar"]],
    [["Macedonia",2012],["Kaliopi","Crno i belo"]],
    [["the Netherlands",2012],["Joan Franka","You and Me"]],
    [["Malta",2012],["Kurt Calleja","This Is the Night"]],
    [["Belarus",2012],["Litesound","We Are the Heroes"]],
    [["Portugal",2012],["Filipa Sousa","Vida minha"]],
    [["Ukraine",2012],["Gaitana","Be My Guest"]],
    [["Bulgaria",2012],["Sofi Marinova","Love Unlimited"]],
    [["Slovenia",2012],["Eva Boto","Verjamem"]],
    [["Croatia",2012],["Nina Badric","Nebo"]],
    [["Sweden",2012],["Loreen","Euphoria"]],
    [["Georgia",2012],["Anri Jokhadze","I'm a Joker"]],
    [["Turkey",2012],["Can Bonomo","Love Me Back"]],
    [["Estonia",2012],["Ott Lepland","Kuula"]],
    [["Slovakia",2012],["Max Jason Mai","Don't Close Your Eyes"]],
    [["Norway",2012],["Tooji","Stay"]],
    [["Bosnia and Herzegovina",2012],["Maya Sar","Korake ti znam"]],
    [["Lithuania",2012],["Donny Montell","Love Is Blind"]],
    [["the United Kingdom",2012],["Engelbert Humperdinck","Love Will Set You Free"]],
    [["France",2012],["Anggun","Echo (You and I)"]],
    [["Italy",2012],["Nina Zilli","L'amore e femmina (Out of Love)"]],
    [["Azerbaijan",2012],["Sabina Babayeva","When the Music Dies"]],
    [["Spain",2012],["Pastora Soler","Quedate conmigo"]],
    [["Germany",2012],["Roman Lob","Standing Still"]],
    [["Austria",2013],["Natalia Kelly","Shine"]],
    [["Estonia",2013],["Birgit","Et uus saaks alguse"]],
    [["Slovenia",2013],["Hannah","Straight into Love"]],
    [["Croatia",2013],["Klapa s Mora","Mizerja"]],
    [["Denmark",2013],["Emmelie de Forest","Only Teardrops"]],
    [["Russia",2013],["Dina Garipova","What If"]],
    [["Ukraine",2013],["Zlata Ognevich","Gravity"]],
    [["the Netherlands",2013],["Anouk","Birds"]],
    [["Montenegro",2013],["Who See","Igranka"]],
    [["Lithuania",2013],["Andrius Pojavis","Something"]],
    [["Belarus",2013],["Alyona Lanskaya","Solayoh"]],
    [["Moldova",2013],["Aliona Moon","O mie"]],
    [["Ireland",2013],["Ryan Dolan","Only Love Survives"]],
    [["Cyprus",2013],["Despina Olympiou","An me thimasai"]],
    [["Belgium",2013],["Roberto Bellarosa","Love Kills"]],
    [["Serbia",2013],["Moje 3","Ljubav je svuda"]],
    [["Latvia",2013],["PeR","Here We Go"]],
    [["San Marino",2013],["Valentina Monetta","Crisalide (Vola)"]],
    [["Macedonia",2013],["Esma and Lozano","Pred da se razdeni"]],
    [["Azerbaijan",2013],["Farid Mammadov","Hold Me"]],
    [["Finland",2013],["Krista Siegfrids","Marry Me"]],
    [["Malta",2013],["Gianluca","Tomorrow"]],
    [["Bulgaria",2013],["Elitsa Todorova and Stoyan Yankoulov","Samo shampioni"]],
    [["Iceland",2013],["Eythor Ingi","Eg a lif"]],
    [["Greece",2013],["Koza Mostra feat. Agathon Iakovidis","Alcohol Is Free"]],
    [["Israel",2013],["Moran Mazor","Rak Bishvilo"]],
    [["Armenia",2013],["Dorians","Lonely Planet"]],
    [["Hungary",2013],["ByeAlex","Kedvesem"]],
    [["Norway",2013],["Margaret Berger","I Feed You My Love"]],
    [["Albania",2013],["Adrian Lulgjuraj and Bledar Sejko","Identitet"]],
    [["Georgia",2013],["Nodi Tatishvili and Sophie Gelovani","Waterfall"]],
    [["Switzerland",2013],["Takasa","You and Me"]],
    [["Romania",2013],["Cezar","It's My Life"]],
    [["France",2013],["Amandine Bourgeois","L'Enfer et moi"]],
    [["Spain",2013],["ESDM","Contigo hasta el final"]],
    [["Germany",2013],["Cascada","Glorious"]],
    [["the United Kingdom",2013],["Bonnie Tyler","Believe in Me"]],
    [["Sweden",2013],["Robin Stjernberg","You"]],
    [["Italy",2013],["Marco Mengoni","L'essenziale"]],
    [["Armenia",2014],["Aram Mp3","Not Alone"]],
    [["Latvia",2014],["Aarzemnieki","Cake to Bake"]],
    [["Estonia",2014],["Tanja","Amazing"]],
    [["Sweden",2014],["Sanna Nielsen","Undo"]],
    [["Iceland",2014],["Pollaponk","No Prejudice"]],
    [["Albania",2014],["Hersi","One Night's Anger"]],
    [["Russia",2014],["Tolmachevy Sisters","Shine"]],
    [["Azerbaijan",2014],["Dilara Kazimova","Start a Fire"]],
    [["Ukraine",2014],["Mariya Yaremchuk","Tick-Tock"]],
    [["Belgium",2014],["Axel Hirsoux","Mother"]],
    [["Moldova",2014],["Cristina Scarlat","Wild Soul"]],
    [["San Marino",2014],["Valentina Monetta","Maybe"]],
    [["Portugal",2014],["Suzy","Quero ser tua"]],
    [["the Netherlands",2014],["The Common Linnets","Calm After the Storm"]],
    [["Montenegro",2014],["Sergej Cetkovic","Moj svijet"]],
    [["Hungary",2014],["Andras Kallay-Saunders","Running"]],
    [["Malta",2014],["Firelight","Coming Home"]],
    [["Israel",2014],["Mei Finegold","Same Heart"]],
    [["Norway",2014],["Carl Espen","Silent Storm"]],
    [["Georgia",2014],["The Shin and Mariko","Three Minutes to Earth"]],
    [["Poland",2014],["Donatan and Cleo","My Slowianie - We Are Slavic"]],
    [["Austria",2014],["Conchita Wurst","Rise Like a Phoenix"]],
    [["Lithuania",2014],["Vilija","Attention"]],
    [["Finland",2014],["Softengine","Something Better"]],
    [["Ireland",2014],["Can-linn feat. Kasey Smith","Heartbeat"]],
    [["Belarus",2014],["Teo","Cheesecake"]],
    [["Macedonia",2014],["Tijana","To the Sky"]],
    [["Switzerland",2014],["Sebalter","Hunter of Stars"]],
    [["Greece",2014],["Freaky Fortune feat. RiskyKidd","Rise Up"]],
    [["Slovenia",2014],["Tinkara Kovac","Round and Round"]],
    [["Romania",2014],["Paula Seling and Ovi","Miracle"]],
    [["Germany",2014],["Elaiza","Is It Right"]],
    [["France",2014],["Twin Twin","Moustache"]],
    [["Italy",2014],["Emma","La mia citta"]],
    [["Spain",2014],["Ruth Lorenzo","Dancing in the Rain"]],
    [["Denmark",2014],["Basim","Cliche Love Song"]],
    [["the United Kingdom",2014],["Molly","Children of the Universe"]],
    [["Moldova",2015],["Eduard Romanyuta","I Want Your Love"]],
    [["Armenia",2015],["Genealogy","Face the Shadow"]],
    [["Belgium",2015],["Loic Nottet","Rhythm Inside"]],
    [["the Netherlands",2015],["Trijntje Oosterhuis","Walk Along"]],
    [["Finland",2015],["Pertti Kurikan Nimipaivat","Aina mun pitaa"]],
    [["Greece",2015],["Maria Elena Kyriakou","One Last Breath"]],
    [["Estonia",2015],["Elina Born and Stig Rasta","Goodbye to Yesterday"]],
    [["Macedonia",2015],["Daniel Kajmakoski","Autumn Leaves"]],
    [["Serbia",2015],["Bojana Stamenov","Beauty Never Lies"]],
    [["Hungary",2015],["Boggie","Wars for Nothing"]],
    [["Belarus",2015],["Uzari and Maimuna","Time"]],
    [["Russia",2015],["Polina Gagarina","A Million Voices"]],
    [["Denmark",2015],["Anti Social Media","The Way You Are"]],
    [["Albania",2015],["Elhaida Dani","I'm Alive"]],
    [["Romania",2015],["Voltaj","De la capat"]],
    [["Georgia",2015],["Nina Sublatti","Warrior"]],
    [["Lithuania",2015],["Monika Linkyte and Vaidas Baumila","This Time"]],
    [["Ireland",2015],["Molly Sterling","Playing with Numbers"]],
    [["San Marino",2015],["Anita Simoncini and Michele Perniola","Chain of Lights"]],
    [["Montenegro",2015],["Knez","Adio"]],
    [["Malta",2015],["Amber","Warrior"]],
    [["Norway",2015],["Morland and Debrah Scarlett","A Monster Like Me"]],
    [["Portugal",2015],["Leonor Andrade","Ha um mar que nos separa"]],
    [["Czech Republic",2015],["Marta Jandova and Vaclav Noid Barta","Hope Never Dies"]],
    [["Israel",2015],["Nadav Guedj","Golden Boy"]],
    [["Latvia",2015],["Aminata","Love Injected"]],
    [["Azerbaijan",2015],["Elnur Huseynov","Hour of the Wolf"]],
    [["Iceland",2015],["Maria Olafs","Unbroken"]],
    [["Sweden",2015],["Mans Zelmerlow","Heroes"]],
    [["Switzerland",2015],["Melanie Rene","Time to Shine"]],
    [["Cyprus",2015],["John Karayiannis","One Thing I Should Have Done"]],
    [["Slovenia",2015],["Maraaya","Here for You"]],
    [["Poland",2015],["Monika Kuszynska","In the Name of Love"]],
    [["France",2015],["Lisa Angell","N'oubliez pas"]],
    [["the United Kingdom",2015],["Electro Velvet","Still in Love with You"]],
    [["Australia",2015],["Guy Sebastian","Tonight Again"]],
    [["Austria",2015],["The Makemakes","I Am Yours"]],
    [["Germany",2015],["Ann Sophie","Black Smoke"]],
    [["Spain",2015],["Edurne","Amanecer"]],
    [["Italy",2015],["Il Volo","Grande amore"]],
    [["Finland",2016],["Sandhja","Sing It Away"]],
    [["Greece",2016],["Argo","Utopian Land"]],
    [["Moldova",2016],["Lidia Isac","Falling Stars"]],
    [["Hungary",2016],["Freddie","Pioneer"]],
    [["Croatia",2016],["Nina Kraljic","Lighthouse"]],
    [["the Netherlands",2016],["Douwe Bob","Slow Down"]],
    [["Armenia",2016],["Iveta Mukuchyan","LoveWave"]],
    [["San Marino",2016],["Serhat","I Didn't Know"]],
    [["Russia",2016],["Sergey Lazarev","You Are the Only One"]],
    [["Czech Republic",2016],["Gabriela Guncikova","I Stand"]],
    [["Cyprus",2016],["Minus One","Alter Ego"]],
    [["Austria",2016],["Zoe","Loin d'ici"]],
    [["Estonia",2016],["Juri Pootsmann","Play"]],
    [["Azerbaijan",2016],["Samra","Miracle"]],
    [["Montenegro",2016],["Highway","The Real Thing"]],
    [["Iceland",2016],["Greta Salome","Hear Them Calling"]],
    [["Bosnia and Herzegovina",2016],["Dalal and Deen feat. Ana Rucner and Jala","Ljubav je"]],
    [["Malta",2016],["Ira Losco","Walk on Water"]],
    [["Latvia",2016],["Justs","Heartbeat"]],
    [["Poland",2016],["Michal Szpak","Color of Your Life"]],
    [["Switzerland",2016],["Rykka","The Last of Our Kind"]],
    [["Israel",2016],["Hovi Star","Made of Stars"]],
    [["Belarus",2016],["Ivan","Help You Fly"]],
    [["Serbia",2016],["Sanja Vucic Zaa","Goodbye (Shelter)"]],
    [["Ireland",2016],["Nicky Byrne","Sunlight"]],
    [["Macedonia",2016],["Kaliopi","Dona"]],
    [["Lithuania",2016],["Donny Montell","I've Been Waiting for This Night"]],
    [["Australia",2016],["Dami Im","Sound of Silence"]],
    [["Slovenia",2016],["ManuElla","Blue and Red"]],
    [["Bulgaria",2016],["Poli Genova","If Love Was a Crime"]],
    [["Denmark",2016],["Lighthouse X","Soldiers of Love"]],
    [["Ukraine",2016],["Jamala","1944"]],
    [["Norway",2016],["Agnete","Icebreaker"]],
    [["Georgia",2016],["Nika Kocharov and Young Georgian Lolitaz","Midnight Gold"]],
    [["Albania",2016],["Eneda Tarifa","Fairytale"]],
    [["Belgium",2016],["Laura Tesoro","What's the Pressure"]],
    [["Italy",2016],["Francesca Michielin","No Degree of Separation"]],
    [["Sweden",2016],["Frans","If I Were Sorry"]],
    [["Germany",2016],["Jamie-Lee","Ghost"]],
    [["France",2016],["Amir","J'ai cherche"]],
    [["Spain",2016],["Barei","Say Yay!"]],
    [["the United Kingdom",2016],["Joe and Jake","You're Not Alone"]],
    [["Sweden",2017],["Robin Bengtsson","I Can't Go On"]],
    [["Georgia",2017],["Tamara Gachechiladze","Keep the Faith"]],
    [["Australia",2017],["Isaiah","Don't Come Easy"]],
    [["Albania",2017],["Lindita","World"]],
    [["Belgium",2017],["Blanche","City Lights"]],
    [["Montenegro",2017],["Slavko Kalezic","Space"]],
    [["Finland",2017],["Norma John","Blackbird"]],
    [["Azerbaijan",2017],["Dihaj","Skeletons"]],
    [["Portugal",2017],["Salvador Sobral","Amar pelos dois"]],
    [["Greece",2017],["Demy","This Is Love"]],
    [["Poland",2017],["Kasia Mos","Flashlight"]],
    [["Moldova",2017],["SunStroke Project","Hey Mamma"]],
    [["Iceland",2017],["Svala","Paper"]],
    [["Czech Republic",2017],["Martina Barta","My Turn"]],
    [["Cyprus",2017],["Hovig","Gravity"]],
    [["Armenia",2017],["Artsvik","Fly with Me"]],
    [["Slovenia",2017],["Omar Naber","On My Way"]],
    [["Latvia",2017],["Triana Park","Line"]],
    [["Serbia",2017],["Tijana Bogicevic","In Too Deep"]],
    [["Austria",2017],["Nathan Trent","Running on Air"]],
    [["Macedonia",2017],["Jana Burceska","Dance Alone"]],
    [["Malta",2017],["Claudia Faniello","Breathlessly"]],
    [["Romania",2017],["Ilinca feat. Alex Florea","Yodel It!"]],
    [["the Netherlands",2017],["OG3NE","Lights and Shadows"]],
    [["Hungary",2017],["Joci Papai","Origo"]],
    [["Denmark",2017],["Anja","Where I Am"]],
    [["Ireland",2017],["Brendan Murray","Dying to Try"]],
    [["San Marino",2017],["Valentina Monetta and Jimmie Wilson","Spirit of the Night"]],
    [["Croatia",2017],["Jacques Houdek","My Friend"]],
    [["Norway",2017],["Jowst[aa]","Grab the Moment"]],
    [["Switzerland",2017],["Timebelle","Apollo"]],
    [["Belarus",2017],["Naviband","Story of My Life"]],
    [["Bulgaria",2017],["Kristian Kostov","Beautiful Mess"]],
    [["Lithuania",2017],["Fusedmarc","Rain of Revolution"]],
    [["Estonia",2017],["Koit Toome and Laura","Verona"]],
    [["Israel",2017],["Imri","I Feel Alive"]],
    [["Italy",2017],["Francesco Gabbani","Occidentali's Karma"]],
    [["Spain",2017],["Manel Navarro","Do It for Your Lover"]],
    [["the United Kingdom",2017],["Lucie Jones","Never Give Up on You"]],
    [["Germany",2017],["Levina","Perfect Life"]],
    [["Ukraine",2017],["O.Torvald","Time"]],
    [["France",2017],["Alma","Requiem"]],
    [["Azerbaijan",2018],["Aisel","X My Heart"]],
    [["Iceland",2018],["Ari Olafsson","Our Choice"]],
    [["Albania",2018],["Eugent Bushpepa","Mall"]],
    [["Belgium",2018],["Sennek","A Matter of Time"]],
    [["Czech Republic",2018],["Mikolas Josef","Lie to Me"]],
    [["Lithuania",2018],["Ieva Zasimauskaite","When We're Old"]],
    [["Israel",2018],["Netta","Toy"]],
    [["Belarus",2018],["Alekseev","Forever"]],
    [["Estonia",2018],["Elina Nechayeva","La forza"]],
    [["Bulgaria",2018],["Equinox","Bones"]],
    [["Macedonia",2018],["Eye Cue","Lost and Found"]],
    [["Croatia",2018],["Franka","Crazy"]],
    [["Austria",2018],["Cesar Sampson","Nobody but You"]],
    [["Greece",2018],["Yianna Terzi","Oniro mou"]],
    [["Finland",2018],["Saara Aalto","Monsters"]],
    [["Armenia",2018],["Sevak Khanagyan","Qami"]],
    [["Switzerland",2018],["Zibbz","Stones"]],
    [["Ireland",2018],["Ryan O'Shaughnessy","Together"]],
    [["Cyprus",2018],["Eleni Foureira","Fuego"]],
    [["Norway",2018],["Alexander Rybak","That's How You Write a Song"]],
    [["Romania",2018],["The Humans","Goodbye"]],
    [["Serbia",2018],["Sanja Ilic and Balkanika","Nova deca"]],
    [["San Marino",2018],["Jessika feat. Jenifer Brening","Who We Are"]],
    [["Denmark",2018],["Rasmussen","Higher Ground"]],
    [["Russia",2018],["Julia Samoylova","I Won't Break"]],
    [["Moldova",2018],["DoReDoS","My Lucky Day"]],
    [["the Netherlands",2018],["Waylon","Outlaw in 'Em"]],
    [["Australia",2018],["Jessica Mauboy","We Got Love"]],
    [["Georgia",2018],["Ethno-Jazz Band Iriao","For You"]],
    [["Poland",2018],["Gromee feat. Lukas Meijer","Light Me Up"]],
    [["Malta",2018],["Christabelle","Taboo"]],
    [["Hungary",2018],["AWS","Viszlat nyar"]],
    [["Latvia",2018],["Laura Rizzotto","Funny Girl"]],
    [["Sweden",2018],["Benjamin Ingrosso","Dance You Off"]],
    [["Montenegro",2018],["Vanja Radovanovic","Inje"]],
    [["Slovenia",2018],["Lea Sirk","Hvala, ne!"]],
    [["Ukraine",2018],["Melovin","Under the Ladder"]],
    [["Spain",2018],["Amaia and Alfred","Tu cancion"]],
    [["Portugal",2018],["Claudia Pascoal[ai]","O jardim"]],
    [["the United Kingdom",2018],["SuRie","Storm"]],
    [["Germany",2018],["Michael Schulte","You Let Me Walk Alone"]],
    [["France",2018],["Madame Monsieur","Mercy"]],
    [["Italy",2018],["Ermal Meta and Fabrizio Moro","Non mi avete fatto niente"]],
    [["Cyprus",2019],["Tamta","Replay"]],
    [["Montenegro",2019],["D mol","Heaven"]],
    [["Finland",2019],["Darude feat. Sebastian Rejman","Look Away"]],
    [["Poland",2019],["Tulia","Fire of Love (Pali sie)"]],
    [["Slovenia",2019],["Zala Kralj and Gasper Santl","Sebi"]],
    [["Czech Republic",2019],["Lake Malawi","Friend of a Friend"]],
    [["Hungary",2019],["Joci Papai","Az en apam"]],
    [["Belarus",2019],["Zena","Like It"]],
    [["Serbia",2019],["Nevena Bozovic","Kruna"]],
    [["Belgium",2019],["Eliot","Wake Up"]],
    [["Georgia",2019],["Oto Nemsadze","Keep On Going"]],
    [["Australia",2019],["Kate Miller-Heidke","Zero Gravity"]],
    [["Iceland",2019],["Hatari","Hatrid mun sigra"]],
    [["Estonia",2019],["Victor Crone","Storm"]],
    [["Portugal",2019],["Conan Osiris","Telemoveis"]],
    [["Greece",2019],["Katerine Duska","Better Love"]],
    [["San Marino",2019],["Serhat","Say Na Na Na"]],
    [["Armenia",2019],["Srbuk","Walking Out"]],
    [["Ireland",2019],["Sarah McTernan","22"]],
    [["Moldova",2019],["Anna Odobescu","Stay"]],
    [["Switzerland",2019],["Luca Hanni","She Got Me"]],
    [["Latvia",2019],["Carousel","That Night"]],
    [["Romania",2019],["Ester Peony","On a Sunday"]],
    [["Denmark",2019],["Leonora","Love Is Forever"]],
    [["Sweden",2019],["John Lundvik","Too Late for Love"]],
    [["Austria",2019],["Paenda","Limits"]],
    [["Croatia",2019],["Roko","The Dream"]],
    [["Malta",2019],["Michela","Chameleon"]],
    [["Lithuania",2019],["Jurij Veklenko","Run with the Lions"]],
    [["Russia",2019],["Sergey Lazarev","Scream"]],
    [["Albania",2019],["Jonida Maliqi","Ktheju tokes"]],
    [["Norway",2019],["Keiino","Spirit in the Sky"]],
    [["the Netherlands",2019],["Duncan Laurence","Arcade"]],
    [["North Macedonia",2019],["Tamara Todevska","Proud"]],
    [["Azerbaijan",2019],["Chingiz","Truth"]],
    [["Germany",2019],["S!sters","Sister"]],
    [["Israel",2019],["Kobi Marimi","Home"]],
    [["the United Kingdom",2019],["Michael Rice","Bigger than Us"]],
    [["France",2019],["Bilal Hassani","Roi"]],
    [["Italy",2019],["Mahmood","Soldi"]],
    [["Spain",2019],["Miki","La venda"]],
    [["Lithuania",2021],["The Roop","Discoteque"]],
    [["Slovenia",2021],["Ana Soklic","Amen"]],
    [["Russia",2021],["Manizha","Russian Woman"]],
    [["Sweden",2021],["Tusse","Voices"]],
    [["Australia",2021],["Montaigne","Technicolour"]],
    [["North Macedonia",2021],["Vasil","Here I Stand"]],
    [["Ireland",2021],["Lesley Roy","Maps"]],
    [["Cyprus",2021],["Elena Tsagrinou","El Diablo"]],
    [["Norway",2021],["Tix","Fallen Angel"]],
    [["Croatia",2021],["Albina","Tick-Tock"]],
    [["Belgium",2021],["Hooverphonic","The Wrong Place"]],
    [["Israel",2021],["Eden Alene","Set Me Free"]],
    [["Romania",2021],["Roxen","Amnesia"]],
    [["Azerbaijan",2021],["Efendi","Mata Hari"]],
    [["Ukraine",2021],["Go_A","Shum"]],
    [["Malta",2021],["Destiny","Je me casse"]],
    [["San Marino",2021],["Senhit[am]","Adrenalina"]],
    [["Estonia",2021],["Uku Suviste","The Lucky One"]],
    [["Czech Republic",2021],["Benny Cristo","Omaga"]],
    [["Greece",2021],["Stefania","Last Dance"]],
    [["Austria",2021],["Vincent Bueno","Amen"]],
    [["Poland",2021],["Rafal","The Ride"]],
    [["Moldova",2021],["Natalia Gordienko","Sugar"]],
    [["Iceland",2021],["Dadi og Gagnamagnid","10 Years"]],
    [["Serbia",2021],["Hurricane","Loco loco"]],
    [["Georgia",2021],["Tornike Kipiani","You"]],
    [["Albania",2021],["Anxhela Peristeri","Karma"]],
    [["Portugal",2021],["The Black Mamba","Love Is on My Side"]],
    [["Bulgaria",2021],["Victoria","Growing Up Is Getting Old"]],
    [["Finland",2021],["Blind Channel","Dark Side"]],
    [["Latvia",2021],["Samanta Tina","The Moon Is Rising"]],
    [["Switzerland",2021],["Gjon's Tears","Tout l'univers"]],
    [["Denmark",2021],["Fyr og Flamme","Ove os pa hinanden"]],
    [["the United Kingdom",2021],["James Newman","Embers"]],
    [["Spain",2021],["Blas Canto","Voy a quedarme"]],
    [["Germany",2021],["Jendrik","I Don't Feel Hate"]],
    [["France",2021],["Barbara Pravi","Voila"]],
    [["the Netherlands",2021],["Jeangu Macrooy","Birth of a New Age"]],
    [["Italy",2021],["Maneskin","Zitti e buoni"]],
    [["Albania",2022],["Ronela Hajati","Sekret"]],
    [["Latvia",2022],["Citi Zeni","Eat Your Salad"]],
    [["Lithuania",2022],["Monika Liu","Sentimentai"]],
    [["Switzerland",2022],["Marius Bear","Boys Do Cry"]],
    [["Slovenia",2022],["LPS","Disko"]],
    [["Ukraine",2022],["Kalush Orchestra","Stefania"]],
    [["Bulgaria",2022],["Intelligent Music Project","Intention"]],
    [["the Netherlands",2022],["S10","De diepte"]],
    [["Moldova",2022],["Zdob si Zdub and Advahov Brothers","Trenuletul"]],
    [["Portugal",2022],["Maro","Saudade, saudade"]],
    [["Croatia",2022],["Mia Dimsic","Guilty Pleasure"]],
    [["Denmark",2022],["Reddi","The Show"]],
    [["Austria",2022],["Lumix feat. Pia Maria","Halo"]],
    [["Iceland",2022],["Systur","Med haekkandi sol"]],
    [["Greece",2022],["Amanda Georgiadi Tenfjord","Die Together"]],
    [["Norway",2022],["Subwoolfer","Give That Wolf a Banana"]],
    [["Armenia",2022],["Rosa Linn","Snap"]],
    [["Finland",2022],["The Rasmus","Jezebel"]],
    [["Israel",2022],["Michael Ben David","I.M"]],
    [["Serbia",2022],["Konstrakta","In corpore sano"]],
    [["Azerbaijan",2022],["Nadir Rustamli","Fade to Black"]],
    [["Georgia",2022],["Circus Mircus","Lock Me In"]],
    [["Malta",2022],["Emma Muscat","I Am What I Am"]],
    [["San Marino",2022],["Achille Lauro","Stripper"]],
    [["Australia",2022],["Sheldon Riley","Not the Same"]],
    [["Cyprus",2022],["Andromache","Ela"]],
    [["Ireland",2022],["Brooke","That's Rich"]],
    [["North Macedonia",2022],["Andrea","Circles"]],
    [["Estonia",2022],["Stefan","Hope"]],
    [["Romania",2022],["Wrs","Llamame"]],
    [["Poland",2022],["Ochman","River"]],
    [["Montenegro",2022],["Vladana","Breathe"]],
    [["Belgium",2022],["Jeremie Makiese","Miss You"]],
    [["Sweden",2022],["Cornelia Jakobs","Hold Me Closer"]],
    [["Czech Republic",2022],["We Are Domi","Lights Off"]],
    [["France",2022],["Alvan and Ahez","Fulenn"]],
    [["Italy",2022],["Mahmood and Blanco","Brividi"]],
    [["Spain",2022],["Chanel","SloMo"]],
    [["Germany",2022],["Malik Harris","Rockstars"]],
    [["the United Kingdom",2022],["Sam Ryder","Space Man"]],
    [["Norway",2023],["Alessandra","Queen of Kings"]],
    [["Malta",2023],["The Busker","Dance (Our Own Party)"]],
    [["Serbia",2023],["Luke Black","Samo mi se spava"]],
    [["Latvia",2023],["Sudden Lights","Aija"]],
    [["Portugal",2023],["Mimicat","Ai coracao"]],
    [["Ireland",2023],["Wild Youth","We Are One"]],
    [["Croatia",2023],["Let 3","Mama SC!"]],
    [["Switzerland",2023],["Remo Forrer","Watergun"]],
    [["Israel",2023],["Noa Kirel","Unicorn"]],
    [["Moldova",2023],["Pasha Parfeni","Soarele si luna"]],
    [["Sweden",2023],["Loreen","Tattoo"]],
    [["Azerbaijan",2023],["TuralTuranX","Tell Me More"]],
    [["Czechia",2023],["Vesna","My Sister's Crown"]],
    [["the Netherlands",2023],["Mia Nicolai and Dion Cooper","Burning Daylight"]],
    [["Finland",2023],["Kaarija","Cha Cha Cha"]],
    [["Denmark",2023],["Reiley","Breaking My Heart"]],
    [["Armenia",2023],["Brunette","Future Lover"]],
    [["Romania",2023],["Theodor Andrei","D.G.T. (Off and On)"]],
    [["Estonia",2023],["Alika","Bridges"]],
    [["Belgium",2023],["Gustaph","Because of You"]],
    [["Cyprus",2023],["Andrew Lambrou","Break a Broken Heart"]],
    [["Iceland",2023],["Dilja","Power"]],
    [["Greece",2023],["Victor Vernicos","What They Say"]],
    [["Poland",2023],["Blanka","Solo"]],
    [["Slovenia",2023],["Joker Out","Carpe Diem"]],
    [["Georgia",2023],["Iru","Echo"]],
    [["San Marino",2023],["Piqued Jacks","Like an Animal"]],
    [["Austria",2023],["Teya and Salena","Who the Hell Is Edgar?"]],
    [["Albania",2023],["Albina and Familja Kelmendi","Duje"]],
    [["Lithuania",2023],["Monika Linkyte","Stay"]],
    [["Australia",2023],["Voyager","Promise"]],
    [["France",2023],["La Zarra","Evidemment"]],
    [["Spain",2023],["Blanca Paloma","Eaea"]],
    [["Italy",2023],["Marco Mengoni","Due vite"]],
    [["Ukraine",2023],["Tvorchi","Heart of Steel"]],
    [["Germany",2023],["Lord of the Lost","Blood & Glitter"]],
    [["the United Kingdom",2023],["Mae Muller","I Wrote a Song"]]
  ]);


